# Generated by Django 5.0.4 on 2025-10-01 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("summary", models.CharField(max_length=280)),
                ("content", models.TextField()),
                (
                    "author_display",
                    models.CharField(default="Starwave Mod Team", max_length=80),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("events", "Events"),
                            ("releases", "Releases"),
                            ("creative", "Creative Projects"),
                            ("behind_the_scenes", "Behind the Scenes"),
                        ],
                        default="general",
                        max_length=32,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ("-is_pinned", "-published_at"),
            },
        ),
    ]
